### ISSUE TITLE
Have experience with GitHub & Git

### ISSUE THREAD

**Issue by Enitishkr** [Enitishkr/GSoC-pgRouting#1]
- [x] Fork the GSoC-pgRouting repository
- [x] activate issues in your fork
- [x] open an issue in your fork and put this content on the issue
- [x] Clone your fork repository in your computer
- [x] Create remote named `upstream` pointing to https://github.com/pgRouting/pgrouting
- [x] checkout to the master branch of `upstream`
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] put link of branch on pgRouting gitter chat
- [x] put link of issue on pgRouting gitter chat

**Comment by Enitishkr** [comment]
**### Create remote named upstream:**
Command:
git remote add upstream https://github.com/pgRouting/pgrouting

**Comment by Enitishkr** [comment]
**checkout to the master branch of upstream**
git fetch upstream
git checkout upstream/master

**Comment by Enitishkr** [comment]
**create new branch with name gsoc-test**
git branch gsoc-test(this creates new branch)
git checkout gsoc-test(Branch 'gsoc-test' set up to track remote branch 'gsoc-test' from 'origin'.)

**Comment by Enitishkr** [comment]
**push the newly created branch**
git push origin gsoc-test

**Comment by cvvergara** [comment]
You did something wrong, because the test branch has pgRouting/GSoC-pgRouting master branch instead of pgRouting/pgrouting master branch

**Comment by Enitishkr** [comment]
git remote add upstream https://github.com/pgRouting/pgrouting
git remote -v

<pre>
origin	https://github.com/Enitishkr/GSoC-pgRouting.git (fetch)
origin	https://github.com/Enitishkr/GSoC-pgRouting.git (push)
upstream	https://github.com/pgRouting/pgrouting (fetch)
upstream	https://github.com/pgRouting/pgrouting (push)
</pre>

git fetch upstream
git checkout upstream/master
git branch --all


<pre>* <font color="#4E9A06">(HEAD detached at upstream/master)</font>
  gsoc-test
  master
  <font color="#CC0000">remotes/origin/HEAD</font> -&gt; origin/master
  <font color="#CC0000">remotes/origin/boost-alg</font>
  <font color="#CC0000">remotes/origin/develop</font>
  <font color="#CC0000">remotes/origin/gsoc-test</font>
  <font color="#CC0000">remotes/origin/master</font>
  <font color="#CC0000">remotes/origin/moore-alg</font>
  <font color="#CC0000">remotes/origin/revert-9-toposort</font>
  <font color="#CC0000">remotes/upstream/develop</font>
  <font color="#CC0000">remotes/upstream/gh-pages</font>
  <font color="#CC0000">remotes/upstream/master</font>
  <font color="#CC0000">remotes/upstream/release/2.5</font>
  <font color="#CC0000">remotes/upstream/release/2.6</font>
</pre>



git checkout gsoc-test
git push origin gsoc-test

**Comment by cvvergara** [comment]
pass
