### ISSUE TITLE
Build Local pgrouting

### ISSUE THREAD

**Issue by Enitishkr** [Enitishkr/GSoC-pgRouting#2]
- [x] Install requirements
- [x] create new branch with name `gsoc-test`
- [x] push the newly created branch
- [x] build locally pgRouting
- [x] put link of issue on pgRouting gitter chat

**Comment by Enitishkr** [comment]
**Install Requirements**
to install pgrouting, we make sure that the following dependencies are met:
1. C and C++  compilers
2. Postgresql 
3. The Boost Graph Library (BGL)
4. CMake

**Comment by Enitishkr** [comment]
**Configuring**
pgRouting uses the cmake system to do the configuration.
mkdir build
cd build
cmake ..
make
sudo make install

all the commands above mentioned were executed.

**Comment by Enitishkr** [comment]
**After executing make**
<pre><font color="#AD7FA8"><b>Scanning dependencies of target components</b></font>
[  1%] <font color="#4E9A06">Building C object src/components/CMakeFiles/components.dir/connectedComponents.c.o</font>
[  2%] <font color="#4E9A06">Building C object src/components/CMakeFiles/components.dir/strongComponents.c.o</font>
[  3%] <font color="#4E9A06">Building C object src/components/CMakeFiles/components.dir/biconnectedComponents.c.o</font>
[  3%] <font color="#4E9A06">Building C object src/components/CMakeFiles/components.dir/articulationPoints.c.o</font>
[  4%] <font color="#4E9A06">Building C object src/components/CMakeFiles/components.dir/bridges.c.o</font>
[  5%] <font color="#4E9A06">Building CXX object src/components/CMakeFiles/components.dir/connectedComponents_driver.cpp.o</font>
[  6%] <font color="#4E9A06">Building CXX object src/components/CMakeFiles/components.dir/strongComponents_driver.cpp.o</font>
[  6%] <font color="#4E9A06">Building CXX object src/components/CMakeFiles/components.dir/biconnectedComponents_driver.cpp.o</font>
[  7%] <font color="#4E9A06">Building CXX object src/components/CMakeFiles/components.dir/articulationPoints_driver.cpp.o</font>
[  8%] <font color="#4E9A06">Building CXX object src/components/CMakeFiles/components.dir/bridges_driver.cpp.o</font>
[  8%] Built target components
<font color="#AD7FA8"><b>Scanning dependencies of target common</b></font>
[  9%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/postgres_connection.c.o</font>
[ 10%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/check_parameters.c.o</font>
[ 10%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/e_report.c.o</font>
[ 11%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/basePath_SSEC.cpp.o</font>
[ 12%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/points_input.c.o</font>
[ 13%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/matrixRows_input.c.o</font>
[ 13%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/get_check_data.c.o</font>
[ 14%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/edges_input.c.o</font>
[ 15%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/orders_input.c.o</font>
[ 16%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/vehicles_input.c.o</font>
[ 16%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/restrictions_input.c.o</font>
[ 17%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/coordinates_input.c.o</font>
[ 18%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/arrays_input.c.o</font>
[ 19%] <font color="#4E9A06">Building C object src/common/CMakeFiles/common.dir/time_msg.c.o</font>
[ 19%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/pgr_assert.cpp.o</font>
[ 20%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/identifier.cpp.o</font>
[ 21%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/basic_vertex.cpp.o</font>
[ 21%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/xy_vertex.cpp.o</font>
[ 22%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/ch_vertex.cpp.o</font>
[ 23%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/ch_edge.cpp.o</font>
[ 24%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/basic_edge.cpp.o</font>
[ 24%] <font color="#4E9A06">Building CXX object src/common/CMakeFiles/common.dir/pgr_alloc.cpp.o</font>
[ 24%] Built target common
<font color="#AD7FA8"><b>Scanning dependencies of target dijkstra</b></font>
[ 25%] <font color="#4E9A06">Building C object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstra.c.o</font>
[ 26%] <font color="#4E9A06">Building C object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstraVia.c.o</font>
[ 27%] <font color="#4E9A06">Building CXX object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstra_driver.cpp.o</font>
[ 27%] <font color="#4E9A06">Building CXX object src/dijkstra/CMakeFiles/dijkstra.dir/dijkstraVia_driver.cpp.o</font>
[ 27%] Built target dijkstra
<font color="#AD7FA8"><b>Scanning dependencies of target allpairs</b></font>
[ 28%] <font color="#4E9A06">Building C object src/allpairs/CMakeFiles/allpairs.dir/floydWarshall.c.o</font>
[ 29%] <font color="#4E9A06">Building CXX object src/allpairs/CMakeFiles/allpairs.dir/floydWarshall_driver.cpp.o</font>
[ 29%] <font color="#4E9A06">Building C object src/allpairs/CMakeFiles/allpairs.dir/johnson.c.o</font>
[ 30%] <font color="#4E9A06">Building CXX object src/allpairs/CMakeFiles/allpairs.dir/johnson_driver.cpp.o</font>
[ 30%] Built target allpairs
<font color="#AD7FA8"><b>Scanning dependencies of target astar</b></font>
[ 30%] <font color="#4E9A06">Building C object src/astar/CMakeFiles/astar.dir/astar.c.o</font>
[ 31%] <font color="#4E9A06">Building CXX object src/astar/CMakeFiles/astar.dir/astar_driver.cpp.o</font>
[ 31%] Built target astar
<font color="#AD7FA8"><b>Scanning dependencies of target driving_distance</b></font>
[ 32%] <font color="#4E9A06">Building C object src/driving_distance/CMakeFiles/driving_distance.dir/many_to_dist_driving_distance.c.o</font>
[ 33%] <font color="#4E9A06">Building C object src/driving_distance/CMakeFiles/driving_distance.dir/many_to_dist_withPointsDD.c.o</font>
[ 34%] <font color="#4E9A06">Building CXX object src/driving_distance/CMakeFiles/driving_distance.dir/drivedist_driver.cpp.o</font>
[ 34%] <font color="#4E9A06">Building CXX object src/driving_distance/CMakeFiles/driving_distance.dir/withPoints_dd_driver.cpp.o</font>
[ 34%] Built target driving_distance
<font color="#AD7FA8"><b>Scanning dependencies of target ksp</b></font>
[ 35%] <font color="#4E9A06">Building C object src/ksp/CMakeFiles/ksp.dir/ksp.c.o</font>
[ 36%] <font color="#4E9A06">Building C object src/ksp/CMakeFiles/ksp.dir/withPoints_ksp.c.o</font>
[ 36%] <font color="#4E9A06">Building CXX object src/ksp/CMakeFiles/ksp.dir/withPoints_ksp_driver.cpp.o</font>
[ 37%] <font color="#4E9A06">Building CXX object src/ksp/CMakeFiles/ksp.dir/ksp_driver.cpp.o</font>
[ 37%] Built target ksp
<font color="#AD7FA8"><b>Scanning dependencies of target tsp</b></font>
[ 38%] <font color="#4E9A06">Building C object src/tsp/CMakeFiles/tsp.dir/eucledianTSP.c.o</font>
[ 39%] <font color="#4E9A06">Building C object src/tsp/CMakeFiles/tsp.dir/newTSP.c.o</font>
[ 40%] <font color="#4E9A06">Building CXX object src/tsp/CMakeFiles/tsp.dir/newTSP_driver.cpp.o</font>
[ 40%] <font color="#4E9A06">Building CXX object src/tsp/CMakeFiles/tsp.dir/eucledianTSP_driver.cpp.o</font>
[ 41%] <font color="#4E9A06">Building CXX object src/tsp/CMakeFiles/tsp.dir/Dmatrix.cpp.o</font>
[ 42%] <font color="#4E9A06">Building CXX object src/tsp/CMakeFiles/tsp.dir/eucledianDmatrix.cpp.o</font>
[ 43%] <font color="#4E9A06">Building CXX object src/tsp/CMakeFiles/tsp.dir/tour.cpp.o</font>
[ 43%] Built target tsp
<font color="#AD7FA8"><b>Scanning dependencies of target alpha_shape</b></font>
[ 44%] <font color="#4E9A06">Building C object src/alpha_shape/CMakeFiles/alpha_shape.dir/alpha.c.o</font>
[ 45%] <font color="#4E9A06">Building CXX object src/alpha_shape/CMakeFiles/alpha_shape.dir/alpha_driver.cpp.o</font>
In file included from <b>/usr/include/CGAL/Triangulation_euclidean_traits_2.h:28:0</b>,
                 from <b>/home/nitishe/Documents/gsoc2020/GSoC-pgRouting/src/alpha_shape/alpha_driver.cpp:59</b>:
<b>/usr/include/CGAL/internal/deprecation_warning.h:82:6:</b> <font color="#AD7FA8"><b>warning: </b></font>#warning &quot;A deprecated header has been included.&quot; [<font color="#AD7FA8"><b>-Wcpp</b></font>]
 #    <font color="#AD7FA8"><b>warning</b></font> &quot;A deprecated header has been included.&quot;
      <font color="#AD7FA8"><b>^~~~~~~</b></font>
<b>/usr/include/CGAL/internal/deprecation_warning.h:83:54:</b> <font color="#34E2E2"><b>note: </b></font>#pragma message: Warning: The header `&lt;CGAL/Triangulation_euclidean_traits_2.h&gt;` is deprecated.

 #    pragma message (CGAL_INTERNAL_DEPRECATED_MESSAGE<font color="#34E2E2"><b>)</b></font>
                                                      <font color="#34E2E2"><b>^</b></font>
[ 45%] Built target alpha_shape
<font color="#AD7FA8"><b>Scanning dependencies of target bdAstar</b></font>
[ 46%] <font color="#4E9A06">Building C object src/bdAstar/CMakeFiles/bdAstar.dir/bdAstar.c.o</font>
[ 47%] <font color="#4E9A06">Building CXX object src/bdAstar/CMakeFiles/bdAstar.dir/bdAstar_driver.cpp.o</font>
[ 47%] Built target bdAstar
<font color="#AD7FA8"><b>Scanning dependencies of target bdDijkstra</b></font>
[ 47%] <font color="#4E9A06">Building C object src/bdDijkstra/CMakeFiles/bdDijkstra.dir/bdDijkstra.c.o</font>
[ 48%] <font color="#4E9A06">Building CXX object src/bdDijkstra/CMakeFiles/bdDijkstra.dir/bdDijkstra_driver.cpp.o</font>
[ 48%] Built target bdDijkstra
<font color="#AD7FA8"><b>Scanning dependencies of target trsp</b></font>
[ 49%] <font color="#4E9A06">Building C object src/trsp/CMakeFiles/trsp.dir/trsp.c.o</font>
[ 50%] <font color="#4E9A06">Building CXX object src/trsp/CMakeFiles/trsp.dir/trsp_core.cpp.o</font>
[ 51%] <font color="#4E9A06">Building CXX object src/trsp/CMakeFiles/trsp.dir/GraphDefinition.cpp.o</font>
[ 51%] <font color="#4E9A06">Building C object src/trsp/CMakeFiles/trsp.dir/new_trsp.c.o</font>
[ 52%] <font color="#4E9A06">Building CXX object src/trsp/CMakeFiles/trsp.dir/edgeInfo.cpp.o</font>
[ 53%] <font color="#4E9A06">Building CXX object src/trsp/CMakeFiles/trsp.dir/pgr_trspHandler.cpp.o</font>
[ 54%] <font color="#4E9A06">Building CXX object src/trsp/CMakeFiles/trsp.dir/rule.cpp.o</font>
[ 54%] <font color="#4E9A06">Building CXX object src/trsp/CMakeFiles/trsp.dir/trsp_driver.cpp.o</font>
[ 54%] Built target trsp
<font color="#AD7FA8"><b>Scanning dependencies of target max_flow</b></font>
[ 55%] <font color="#4E9A06">Building C object src/max_flow/CMakeFiles/max_flow.dir/max_flow.c.o</font>
[ 56%] <font color="#4E9A06">Building C object src/max_flow/CMakeFiles/max_flow.dir/maximum_cardinality_matching.c.o</font>
[ 56%] <font color="#4E9A06">Building C object src/max_flow/CMakeFiles/max_flow.dir/edge_disjoint_paths.c.o</font>
[ 57%] <font color="#4E9A06">Building CXX object src/max_flow/CMakeFiles/max_flow.dir/max_flow_driver.cpp.o</font>
[ 58%] <font color="#4E9A06">Building CXX object src/max_flow/CMakeFiles/max_flow.dir/maximum_cardinality_matching_driver.cpp.o</font>
[ 59%] <font color="#4E9A06">Building CXX object src/max_flow/CMakeFiles/max_flow.dir/edge_disjoint_paths_driver.cpp.o</font>
[ 59%] <font color="#4E9A06">Building CXX object src/max_flow/CMakeFiles/max_flow.dir/pgr_maxflow.cpp.o</font>
[ 60%] <font color="#4E9A06">Building CXX object src/max_flow/CMakeFiles/max_flow.dir/pgr_flowgraph.cpp.o</font>
[ 60%] Built target max_flow
<font color="#AD7FA8"><b>Scanning dependencies of target contraction</b></font>
[ 61%] <font color="#4E9A06">Building C object src/contraction/CMakeFiles/contraction.dir/contractGraph.c.o</font>
[ 61%] <font color="#4E9A06">Building CXX object src/contraction/CMakeFiles/contraction.dir/contractGraph_driver.cpp.o</font>
[ 61%] Built target contraction
<font color="#AD7FA8"><b>Scanning dependencies of target pickDeliver</b></font>
[ 62%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/base_node.cpp.o</font>
[ 62%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/dnode.cpp.o</font>
[ 63%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/node.cpp.o</font>
[ 64%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/tw_node.cpp.o</font>
[ 65%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/vehicle_node.cpp.o</font>
[ 65%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/order.cpp.o</font>
[ 66%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pd_orders.cpp.o</font>
[ 67%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/fleet.cpp.o</font>
[ 68%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/vehicle.cpp.o</font>
[ 68%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pd_problem.cpp.o</font>
[ 69%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/vehicle_pickDeliver.cpp.o</font>
[ 70%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/book_keeping.cpp.o</font>
[ 70%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/solution.cpp.o</font>
[ 71%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/initial_solution.cpp.o</font>
[ 72%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/optimize.cpp.o</font>
[ 73%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pgr_messages.cpp.o</font>
[ 73%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pgr_pickDeliver.cpp.o</font>
[ 74%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliverEuclidean_driver.cpp.o</font>
[ 75%] <font color="#4E9A06">Building CXX object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliver_driver.cpp.o</font>
[ 76%] <font color="#4E9A06">Building C object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliverEuclidean.c.o</font>
[ 76%] <font color="#4E9A06">Building C object src/pickDeliver/CMakeFiles/pickDeliver.dir/pickDeliver.c.o</font>
[ 76%] Built target pickDeliver
<font color="#AD7FA8"><b>Scanning dependencies of target withPoints</b></font>
[ 76%] <font color="#4E9A06">Building C object src/withPoints/CMakeFiles/withPoints.dir/withPoints.c.o</font>
[ 77%] <font color="#4E9A06">Building CXX object src/withPoints/CMakeFiles/withPoints.dir/get_new_queries.cpp.o</font>
[ 78%] <font color="#4E9A06">Building CXX object src/withPoints/CMakeFiles/withPoints.dir/withPoints_driver.cpp.o</font>
[ 79%] <font color="#4E9A06">Building CXX object src/withPoints/CMakeFiles/withPoints.dir/pgr_withPoints.cpp.o</font>
[ 79%] Built target withPoints
<font color="#AD7FA8"><b>Scanning dependencies of target lineGraph</b></font>
[ 80%] <font color="#4E9A06">Building C object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraphFull.c.o</font>
[ 81%] <font color="#4E9A06">Building CXX object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraphFull_driver.cpp.o</font>
[ 81%] <font color="#4E9A06">Building C object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraph.c.o</font>
[ 82%] <font color="#4E9A06">Building CXX object src/lineGraph/CMakeFiles/lineGraph.dir/lineGraph_driver.cpp.o</font>
[ 82%] Built target lineGraph
<font color="#AD7FA8"><b>Scanning dependencies of target pgrouting-2.6</b></font>
[ 83%] <font color="#8AE234"><b>Linking CXX shared library lib/libpgrouting-2.6.so</b></font>
[ 83%] Built target pgrouting-2.6
<font color="#AD7FA8"><b>Scanning dependencies of target PgRouting_SQL_FILE</b></font>
[ 83%] <font color="#729FCF"><b>Generating pgrouting--2.6.2.sql</b></font>
[ 83%] Built target PgRouting_SQL_FILE
<font color="#AD7FA8"><b>Scanning dependencies of target update_files</b></font>
[ 83%] <font color="#729FCF"><b>Generating pgrouting--2.6.1--2.6.2.sql</b></font>
[ 84%] <font color="#729FCF"><b>Generating pgrouting--2.6.0--2.6.2.sql</b></font>
[ 85%] <font color="#729FCF"><b>Generating pgrouting--2.5.5--2.6.2.sql</b></font>
[ 85%] <font color="#729FCF"><b>Generating pgrouting--2.5.4--2.6.2.sql</b></font>
[ 86%] <font color="#729FCF"><b>Generating pgrouting--2.5.3--2.6.2.sql</b></font>
[ 87%] <font color="#729FCF"><b>Generating pgrouting--2.5.2--2.6.2.sql</b></font>
[ 88%] <font color="#729FCF"><b>Generating pgrouting--2.5.1--2.6.2.sql</b></font>
[ 88%] <font color="#729FCF"><b>Generating pgrouting--2.5.0--2.6.2.sql</b></font>
[ 89%] <font color="#729FCF"><b>Generating pgrouting--2.4.2--2.6.2.sql</b></font>
[ 90%] <font color="#729FCF"><b>Generating pgrouting--2.4.1--2.6.2.sql</b></font>
[ 91%] <font color="#729FCF"><b>Generating pgrouting--2.4.0--2.6.2.sql</b></font>
[ 91%] <font color="#729FCF"><b>Generating pgrouting--2.3.2--2.6.2.sql</b></font>
[ 92%] <font color="#729FCF"><b>Generating pgrouting--2.3.1--2.6.2.sql</b></font>
[ 93%] <font color="#729FCF"><b>Generating pgrouting--2.3.0--2.6.2.sql</b></font>
[ 94%] <font color="#729FCF"><b>Generating pgrouting--2.2.4--2.6.2.sql</b></font>
[ 94%] <font color="#729FCF"><b>Generating pgrouting--2.2.3--2.6.2.sql</b></font>
[ 95%] <font color="#729FCF"><b>Generating pgrouting--2.2.2--2.6.2.sql</b></font>
[ 96%] <font color="#729FCF"><b>Generating pgrouting--2.2.1--2.6.2.sql</b></font>
[ 97%] <font color="#729FCF"><b>Generating pgrouting--2.2.0--2.6.2.sql</b></font>
[ 97%] <font color="#729FCF"><b>Generating pgrouting--2.1.0--2.6.2.sql</b></font>
[ 98%] <font color="#729FCF"><b>Generating pgrouting--2.0.1--2.6.2.sql</b></font>
[ 99%] <font color="#729FCF"><b>Generating pgrouting--2.0.0--2.6.2.sql</b></font>
[100%] Built target update_files
</pre>

**Comment by Enitishkr** [comment]
**after executing sudo make install**
<pre>[sudo] password for nitishe: 
[  8%] Built target components
[ 24%] Built target common
[ 27%] Built target dijkstra
[ 30%] Built target allpairs
[ 31%] Built target astar
[ 34%] Built target driving_distance
[ 37%] Built target ksp
[ 43%] Built target tsp
[ 45%] Built target alpha_shape
[ 47%] Built target bdAstar
[ 48%] Built target bdDijkstra
[ 54%] Built target trsp
[ 60%] Built target max_flow
[ 61%] Built target contraction
[ 76%] Built target pickDeliver
[ 79%] Built target withPoints
[ 82%] Built target lineGraph
[ 83%] Built target pgrouting-2.6
[ 83%] Built target PgRouting_SQL_FILE
[100%] Built target update_files
<font color="#06989A">Install the project...</font>
-- Install configuration: &quot;&quot;
-- Installing: /usr/lib/postgresql/12/lib/libpgrouting-2.6.so
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.6.1--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.6.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.5.5--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.5.4--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.5.3--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.5.2--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.5.1--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.5.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.4.2--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.4.1--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.4.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.3.2--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.3.1--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.3.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.2.4--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.2.3--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.2.2--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.2.1--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.2.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.1.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.0.1--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.0.0--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting--2.6.2.sql
-- Installing: /usr/share/postgresql/12/extension/pgrouting.control

**Comment by Enitishkr** [comment]
**'executing rm -rf * '** 
cmake -DDOC_USE_BOOTSTRAP=ON -DWITH_DOC=ON -DBUILD_DOXY=ON  -DBUILD_LATEX=OFF  ..

i got the output as
<pre>-- CMAKE_BUILD_TYPE 
-- CMAKE_BUILD_TYPE 
-- The C compiler identification is GNU 7.4.0
-- The CXX compiler identification is GNU 7.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- DOXYGEN_MINIMUM_VERSION=1.7
-- SPHINX_MINIMUM_VERSION=1.1
-- POSTGRESQL_MINIMUM_VERSION=9.2.0
-- POSTGIS_MINIMUM_VERSION=2.0.0
-- GNU_CXX_MINIMUM_VERSION=4.6
-- CLANG_CXX_MINIMUM_VERSION=
-- MSVC_CXX_MINIMUM_VERSION=18.0
-- dir=&apos;/home/nitishe/Documents/gsoc2020/GSoC-pgRouting/cmake&apos;
-- Performing Test COMPILER_SUPPORTS_CXX0X
-- Performing Test COMPILER_SUPPORTS_CXX0X - Success
-- Performing Test COMPILER_SUPPORTS_CXX11
-- Performing Test COMPILER_SUPPORTS_CXX11 - Success
-- Using  -std=c++11.
-- Found Perl: /usr/bin/perl (found version &quot;5.26.1&quot;) 
-- POSTGRESQL_PG_CONFIG is /usr/bin/pg_config
-- POSTGRESQL_EXECUTABLE is /usr/lib/postgresql/12/bin/postgres
-- POSTGRESQL_VERSION_STRING in FindPostgreSQL.cmake is PostgreSQL 12.2 (Ubuntu 12.2-2.pgdg18.04+1)
-- POSTGRESQL_INCLUDE_DIR: /usr/include/postgresql/10/server
-- POSTGRESQL_LIBRARIES: /usr/lib/x86_64-linux-gnu
-- PGSQL_VERSION=122
-- Boost version: 1.65.1
-- Boost headers were found here: /usr/include
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   chrono
--   system
--   date_time
--   atomic
-- Boost version: 1.65.1
-- Found the following Boost libraries:
--   thread
--   system
--   chrono
--   date_time
--   atomic
-- CGAL_INCLUDE_DIR=/usr/include
-- CGAL_LIBRARIES=/usr/lib/x86_64-linux-gnu/libCGAL.so
-- BOOST_THREAD_LIBRARIES=/usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so
-- GMP_LIBRARIES=/usr/lib/x86_64-linux-gnu/libgmp.so
-- Found CGAL: /usr/include, /usr/lib/x86_64-linux-gnu/libCGAL.so, /usr/lib/x86_64-linux-gnu/libboost_thread.so;/usr/lib/x86_64-linux-gnu/libboost_system.so;/usr/lib/x86_64-linux-gnu/libboost_chrono.so;/usr/lib/x86_64-linux-gnu/libboost_date_time.so;/usr/lib/x86_64-linux-gnu/libboost_atomic.so;/usr/lib/x86_64-linux-gnu/libpthread.so, /usr/lib/x86_64-linux-gnu/libgmp.so
-- Performing Test C_COMPILER_SUPPORTS_FPIC
-- Performing Test C_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC
-- Performing Test CXX_COMPILER_SUPPORTS_FPIC - Success
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test C_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH
-- Performing Test CXX_COMPILER_SUPPORTS_ROUNDING_MATH - Success
-- Developers documentation.
-- Found Doxygen: /usr/bin/doxygen (found suitable version &quot;1.8.13&quot;, minimum required is &quot;1.7&quot;) found components:  doxygen missing components:  dot
.....OK
-- PgRouting_DOC_TARGETS = html
-- PgRouting_BUILD_LANGUAGES = en
-- SPHINXINTL_LANGUAGE = en
-- Checking for package &apos;Sphinx&apos;
-- Found PythonInterp: /usr/bin/python (found version &quot;2.7.17&quot;) 
-- SPHINX_VERSION Sphinx (sphinx-build) 1.6.7
-- SPHINX_VERSION 1.6.7
-- Found Sphinx: /usr/bin/sphinx-build (Required is at least version &quot;1.1&quot;) 
-- PGR_DOCUMENTATION_BUILD_DIR = /home/nitishe/Documents/gsoc2020/GSoC-pgRouting/build/doc
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nitishe/Documents/gsoc2020/GSoC-pgRouting/build
</pre>

**Comment by cvvergara** [comment]
test pass
