### ISSUE TITLE
Get familiar with C++

### ISSUE THREAD

**Issue by Enitishkr** [Enitishkr/GSoC-pgRouting#5]
- [x] https://www.youtube.com/watch?v=eidEEmGLQcU
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=u5senBJUkPc
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=YnWhqhNdYyk
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=1OEu9C51K2A
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=xnqTKD8uD64
  - [x] Make Report
- [x] https://www.youtube.com/watch?v=86xWVb4XIyE
  - [x] Make Report

**Comment by Enitishkr** [comment]
![WhatsApp Image 2020-03-05 at 8 07 58 PM](https://user-images.githubusercontent.com/60136639/75992898-ad566780-5f1e-11ea-9342-643be951ba14.jpeg)

**Comment by Enitishkr** [comment]
![WhatsApp Image 2020-03-05 at 8 08 19 PM](https://user-images.githubusercontent.com/60136639/75992937-c232fb00-5f1e-11ea-8c6c-13a3ccd27f0d.jpeg)
![WhatsApp Image 2020-03-05 at 8 08 31 PM](https://user-images.githubusercontent.com/60136639/75992948-c65f1880-5f1e-11ea-9df3-ccee1f8931a5.jpeg)

**Comment by Enitishkr** [comment]
![WhatsApp Image 2020-03-05 at 8 08 44 PM](https://user-images.githubusercontent.com/60136639/75992976-d119ad80-5f1e-11ea-88b7-d0354bfe9e78.jpeg)

**Comment by Enitishkr** [comment]
![WhatsApp Image 2020-03-05 at 8 09 15 PM](https://user-images.githubusercontent.com/60136639/75992998-daa31580-5f1e-11ea-9ec4-aaead395c2ce.jpeg)
![WhatsApp Image 2020-03-05 at 8 09 21 PM](https://user-images.githubusercontent.com/60136639/75993009-dd9e0600-5f1e-11ea-8b84-6241fbc2aba0.jpeg)

**Comment by Enitishkr** [comment]
![WhatsApp Image 2020-03-05 at 8 09 30 PM](https://user-images.githubusercontent.com/60136639/75993039-e5f64100-5f1e-11ea-9c94-8d5d9150252c.jpeg)
![WhatsApp Image 2020-03-05 at 8 09 39 PM](https://user-images.githubusercontent.com/60136639/75993045-e8589b00-5f1e-11ea-9192-782242934b33.jpeg)

**Comment by Enitishkr** [comment]
![WhatsApp Image 2020-03-05 at 8 09 06 PM](https://user-images.githubusercontent.com/60136639/75993072-f3133000-5f1e-11ea-8fa2-10bb88fc76b8.jpeg)

**Comment by cvvergara** [comment]
pass
